"""added blacklist tokens

Revision ID: 3e134ab31bc2
Revises: d563ce0e5aab
Create Date: 2025-01-26 21:14:40.956921

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils

# revision identifiers, used by Alembic.
revision = '3e134ab31bc2'
down_revision = 'd563ce0e5aab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('blacklisted_at', sa.Date(), nullable=True),
    sa.Column('id', fastapi_utils.guid_type.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_token')
    # ### end Alembic commands ###
