"""Unique Validation added to room name

Revision ID: 5c11b22e404d
Revises: fcc3886efbb5
Create Date: 2024-05-18 20:53:35.371623

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '5c11b22e404d'
down_revision = 'fcc3886efbb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat_room', ['name'])
    op.sync_enum_values('public', 'chattypeenum', ['one_to_one', 'group', 'Config'],
                        [TableReference(table_schema='public', table_name='chat_room', column_name='room_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'chattypeenum', ['one_to_one', 'group'],
                        [TableReference(table_schema='public', table_name='chat_room', column_name='room_type')],
                        enum_values_to_rename=[])
    op.drop_constraint(None, 'chat_room', type_='unique')
    # ### end Alembic commands ###
